# Generated by Django 3.1.7 on 2021-03-11 20:18

from typing import List

from django.db import migrations

from ..models import create_dynamodb_tables


class Migration(migrations.Migration):

    dependencies: List = []

    operations = [migrations.RunPython(create_dynamodb_tables)]
