# Generated by Django 3.1.7 on 2021-03-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseusermodel',
            name='birthdate',
            field=models.DateField(blank=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='gender',
            field=models.CharField(
                choices=[
                    ('D', 'Please, choice a gender'),
                    ('M', 'Male'),
                    ('F', 'Female'),
                ],
                default='D',
                max_length=1,
                verbose_name='Gender',
            ),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='skype',
            field=models.CharField(blank=True, max_length=50, verbose_name='Skype'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employee',
                to='userapp.contract',
            ),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(auto_now=True, verbose_name='Date of employment'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='structural_unit',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employee',
                to='userapp.structuralunit',
            ),
        ),
    ]
