# Generated by Django 3.1.7 on 2021-03-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20210311_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseusermodel',
            name='birthdate',
            field=models.DateField(auto_now=True, verbose_name='Date of birth'),
        ),
    ]
