# Generated by Django 3.1.7 on 2021-03-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20210311_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformadministrator',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
