# Generated by Django 3.1.7 on 2021-03-14 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_platformadministrator_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSupervisor',
            fields=[
                (
                    'baseusermodel_ptr',
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to='userapp.baseusermodel',
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
            bases=('userapp.baseusermodel',),
        ),
        migrations.RemoveField(
            model_name='employee',
            name='contract_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_employment',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='structural_unit',
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='contract_type',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employee',
                to='userapp.contract',
            ),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='date_of_employment',
            field=models.DateField(auto_now=True, verbose_name='Date of employment'),
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='email',
            field=models.EmailField(
                default='Write an email', max_length=254, verbose_name='Email'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='position',
            field=models.CharField(
                default='Junior', max_length=50, verbose_name='Position'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='baseusermodel',
            name='structural_unit',
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employee',
                to='userapp.structuralunit',
            ),
        ),
        migrations.AddField(
            model_name='moderator',
            name='email',
            field=models.EmailField(
                default='Write an email', max_length=254, verbose_name='Email'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DR', 'Director'),
                    ('PA', 'Platform administrator'),
                    ('MO', 'Moderator'),
                    ('ES', 'Employee supervisor'),
                    ('EM', 'Employee'),
                ],
                max_length=2,
                verbose_name='User role',
            ),
        ),
        migrations.AddField(
            model_name='employee',
            name='supervisor',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='employee',
                to='userapp.employeesupervisor',
            ),
            preserve_default=False,
        ),
    ]
