# Generated by Django 3.1.7 on 2021-03-14 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20210314_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseusermodel',
            name='contract_type',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='userapp_baseusermodel_related_contract',
                to='userapp.contract',
            ),
        ),
        migrations.AlterField(
            model_name='baseusermodel',
            name='structural_unit',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='userapp_baseusermodel_related_unit',
                to='userapp.structuralunit',
            ),
        ),
    ]
