# Generated by Django 3.1.7 on 2021-03-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20210314_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='structuralunit',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
    ]
