# Generated by Django 3.1.7 on 2021-03-17 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_auto_20210314_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseManager',
            fields=[
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name='userapp_warehousemanager_related',
                        serialize=False,
                        to='userapp.user',
                    ),
                ),
                (
                    'middle_name',
                    models.CharField(
                        blank=True, max_length=50, verbose_name='Middle name'
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(
                blank=True,
                choices=[
                    ('DR', 'Director'),
                    ('PA', 'Platform administrator'),
                    ('MO', 'Moderator'),
                    ('ES', 'Employee supervisor'),
                    ('EM', 'Employee'),
                    ('WM', 'Warehouse manager'),
                ],
                max_length=2,
                verbose_name='User role',
            ),
        ),
    ]
