# Generated by Django 3.1.7 on 2021-03-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20210317_0108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderator',
            name='offices',
        ),
        migrations.RemoveField(
            model_name='moderator',
            name='rooms',
        ),
    ]
