# Generated by Django 3.1.7 on 2021-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(verbose_name='Booking start'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reservation_time',
            field=models.DateTimeField(verbose_name='Booking end'),
        ),
    ]
