# Generated by Django 3.1.7 on 2021-03-28 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_auto_20210315_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='headphones',
            field=models.BooleanField(default=False, verbose_name='Headphones'),
        ),
        migrations.AddField(
            model_name='booking',
            name='keyboard',
            field=models.BooleanField(default=False, verbose_name='Keyboard'),
        ),
        migrations.AddField(
            model_name='booking',
            name='laptop',
            field=models.BooleanField(default=False, verbose_name='Laptop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='monitor',
            field=models.BooleanField(default=False, verbose_name='Monitor'),
        ),
    ]
