# Generated by Django 3.1.7 on 2021-04-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_auto_20210328_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date'),
        ),
    ]
